// types/cart.ts

import { Product, Variant } from './product'; // Import your existing types

export interface CartItem {
  _id: string; // The ID of the line item (generated by Mongoose)
  
  // Because we populate() in the controller, these are Objects, not just ID strings
  product: Product; 
  variant?: Variant | null; 
  
  quantity: number;
  price: number; // The price snapshot stored in the item
}

export interface Cart {
  _id: string;
  user: string; // Usually just the ID string unless you populate user
  items: CartItem[];
  totalPrice: number;
  createdAt: string;
  updatedAt: string;
}

// Optional: Type for the API Response structure
export interface CartResponse {
  success: boolean;
  data: Cart;
  message?: string;
}